version: "3.8"

services:
  postgres:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
