quarkus:
  datasource:
    db-kind: postgresql
    jdbc: false
    reactive:
      url: postgresql://localhost:5436/postgres
    username: postgres
    password: postgres
  liquibase:
    migrate-at-start: false
    change-log: db/changeLog.yaml
    validate-on-migrate: false
  log:
    level: INFO
  rest-client:
    dummy-api:
      url: localhost:3000
  default-locale: en-US

mp:
  messaging:
    outgoing:
      show-case-to-dummy:
        connector: smallrye-kafka
        topic: "show-case-to-dummy"
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
    incoming:
      dummy-to-show-case:
        connector: smallrye-kafka
        topic: "dummy-to-show-case"
        value-deserialization-failure-handler: "consumer-failure-handler"

liquibase:
  url: jdbc:postgresql://localhost:5436/postgres

"%test":
   quarkus:
     datasource:
       db-kind: postgresql
       jdbc: false
       reactive:
         url: postgresql://localhost:5555/postgres
       username: postgres
       password: postgres
       devservices:
         enabled: true
         image-name: postgres:12.2-alpine
         db-name: postgres
         username: postgres
         password: postgres
         port: 5555

   liquibase:
     url: jdbc:postgresql://localhost:5555/postgres