quarkus:
  datasource:
    jdbc: false
    db-kind: postgresql
    reactive:
      url: postgresql://localhost:5436/postgres
    username: postgres
    password: postgres
  liquibase:
    migrate-at-start: true
    change-log: db/changeLog.yaml
    validate-on-migrate: false